### ISSUE TITLE
jspm conplication

### ISSUE THREAD

**Issue by daw451-duplicate** [htdt/ng-es6-router#1]
thanks for putting this together looks great but I am having issues with jspm. Don't you think maybe it adds a level of complication that is not necessary? Giving following error but I check file structure and everything is there... looks fine...

Potentially unhandled rejection [3] Error loading "github:angular/bower-angular@1.4.0-build.3962+sha.fe9cd9d" at http://localhost:34909/jspm_packages/github/angular/bower-angular@1.4.0-build.3962+sha.fe9cd9d.js
Error loading "github:angular/bower-angular@1.4.0-build.3962+sha.fe9cd9d" from "app/app" at http://localhost:34909/app/app.js
Not Found: http://localhost:34909/jspm_packages/github/angular/bower-angular@1.4.0-build.3962+sha.fe9cd9d.js (WARNING: non-Error used)

**Comment by htdt** [comment]
jspm is convenient, better bower alternative.
Did you run 
1. `npm install -g jspm`
2. `jspm install`
from the project folder?

**Comment by daw451-duplicate** [comment]
i did actually... the bizarre thing is that the files do exist in the correct location...

**Comment by htdt** [comment]
Looks like it is your server issue. I've added gulp to repo, try to run with it.
